# YOLOv11 Dataset configuration for 挑战杯红外小目标检测
# 阿里云EAIS实例配置版本

# 数据集基础信息
path: .datasets/tiaozhanbei_datasets_final  # 云端数据集根目录
train: images  # 训练图片相对路径
val: images    # 验证图片相对路径
test:                # 测试集路径（可选）

# 类别数量
nc: 6

# 类别名称 (按照索引顺序)
names:
  0: drone      # 无人机
  1: car        # 汽车  
  2: ship       # 船舶
  3: bus        # 公交车
  4: pedestrian # 行人
  5: cyclist    # 骑车人

# 数据集详细信息
info:
  dataset_name: "挑战杯红外小目标检测数据集"
  description: "面向红外图像的小目标检测，包含6类目标"
  version: "1.0"
  year: 2024
  url: ""
  download: ""
  
# 训练参数建议
recommended_settings:
  imgsz: 640          # 推荐图像尺寸
  batch_size: 32      # GPU推荐批次大小  
  epochs: 100         # 推荐训练轮次
  lr0: 0.01          # 推荐初始学习率
  optimizer: "AdamW"  # 推荐优化器

# 数据增强配置
augmentation:
  hsv_h: 0.015       # HSV色调增强
  hsv_s: 0.7         # HSV饱和度增强
  hsv_v: 0.4         # HSV明度增强
  degrees: 0.0       # 旋转角度
  translate: 0.1     # 平移比例
  scale: 0.5         # 缩放比例
  shear: 0.0         # 剪切角度
  perspective: 0.0   # 透视变换
  flipud: 0.0        # 上下翻转概率
  fliplr: 0.5        # 左右翻转概率
  mosaic: 1.0        # 马赛克增强概率
  mixup: 0.0         # Mixup增强概率

# 云端部署配置
cloud_config:
  platform: "阿里云EAIS"
  gpu_type: "T4/V100/A10"
  memory_requirement: "16GB+"
  storage_requirement: "50GB+"
  python_version: "3.8+"
  pytorch_version: "1.12+"
  cuda_version: "11.6+"
